### ISSUE TITLE
Enhance Tag Search and Creation User Experience

### ISSUE THREAD

**Issue by Sweetsuro** [CMU-313/fall23-nodebb-bugbusters#6]
The Tag functionality in NodeBB should be modified to adapt to the course forum setting.

**Acceptance Criteria**
- Instructors/admins can create coursework tags for each category (e.g. hw1, hw2, etc).
- Instructors/admins can create new topics with coursework tags in the Tags webpage.
- Students can only tag posts with existing coursework tags.

**Comment by YuheMa702** [comment]
This feature is fully implemented and tested.
